Fix build portability issue
use pip3 over pip


Former-commit-id: 6ce3edd78ef4b4821244ccc02984d860fbfc93a2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -29,8 +29,8 @@ else
   echo >&2 "'rustup' required for build"
   failed=true
 fi
-command -v pip >/dev/null 2>&1 || {
-  echo >&2 "'pip' (python > 3) required for build"
+command -v pip3 >/dev/null 2>&1 || {
+  echo >&2 "'pip3' required for build"
   failed=true
 }
 command -v wheel >/dev/null 2>&1 || {
