Fix build portability issue
use pip3 over pip


Former-commit-id: cbd1a150adbdd59ae0d1f4864539c24ef18d138a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,7 +34,7 @@ command -v pip3 >/dev/null 2>&1 || {
   failed=true
 }
 command -v wheel >/dev/null 2>&1 || {
-  echo >&2 "'wheel' required for build, try: pip install wheel"
+  echo >&2 "'wheel' required for build, try: pip3 install wheel"
   failed=true
 }
 
